### ISSUE TITLE
Pagination Unavailable

### ISSUE THREAD

**Issue by phyominthu** [MyanmarAPI/partyapi#1]
Hi,

I found party-endpoint is returning bulks of results. Could you please add pagination for this endpoint?

Thanks.

**Comment by tyohan** [comment]
@phyominthu the party list will not more than 100 records. That's the reason we're not use pagination here. And same reason with endpoint url format, also we already have a SDK that make us can't change it for now.

**Comment by phyominthu** [comment]
@tyohan I see. Thanks anyway.
