### ISSUE TITLE
Endpoint URLs not consistent with Candidate and FAQ endpoints

### ISSUE THREAD

**Issue by phyominthu** [MyanmarAPI/partyapi#2]
I'm having an itch to see that party-endpoint does not have same URLs with those from candidate and FAQ endpoints. I have to request `party/` to get the party list while `candidate/list` and `faq/list` do the same work. Another one, `party/detail/<id>` does the same like `candidate/<id>` and `faq/<id>`. It would be better to have consistent URLs like `party/list` and `party/<id>`, I think.

Thanks a lot.

**Comment by tyohan** [comment]
@phyominthu party endpoint and candidate endpoint developed by different developer. And we also already have SDK that use this endpoint. So we can't change it for now. But thanks for your suggestion.

**Comment by phyominthu** [comment]
@tyohan Oh, it's okay then.
