### ISSUE TITLE
More Pagination Meta data

### ISSUE THREAD

**Issue by phyominthu** [MyanmarAPI/partyapi#5]
Hi,

Thanks for adding the pagination. But I think it'd be more complete to add a few more data in the `meta` like `total`, `current_page`, `total_page`.

Meta from **candidate-endpoint** (This has a few more information)
![screen shot 2015-09-14 at 1 05 07 pm](https://cloud.githubusercontent.com/assets/6995089/9843626/277d47d6-5ae2-11e5-9885-6258e6a98cec.png)

Meta data from **party-endpoint**
![screen shot 2015-09-14 at 1 05 31 pm](https://cloud.githubusercontent.com/assets/6995089/9843632/35bbf77a-5ae2-11e5-8b78-b1f2420b60a3.png)

**Comment by phyominthu** [comment]
Thanks for the fix. But API Still not including **total count of Parties**. and `total_pages` is returning null.

**Comment by tyohan** [comment]
@phyominthu it should fine now
